#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Translation Script for File Manager
Translates Turkish text to English in all Python files
"""

import os
import re

# Translation dictionary - Turkish to English
translations = {
    # Common words
    "Dosya": "File",
    "dosya": "file",
    "dosyalar": "files",
    "dosyaları": "files",
    "dosyayı": "file",
    "dosyasını": "file",
    "dosyasını": "file",
    "Klasör": "Folder",
    "klasör": "folder",
    "klasöre": "folder",
    "klasörü": "folder",
    "klasörde": "folder",
    "Kaynak": "Source",
    "kaynak": "source",
    "Hedef": "Target",
    "hedef": "target",
    "Seç": "Select",
    "seç": "select",
    "seçin": "select",
    "seçili": "selected",
    "Değiştir": "Change",
    "değiştir": "change",
    "Geri": "Back",
    "geri": "back",
    "Üst": "Up",
    "üst": "up",
    "Ana": "Home",
    "ana": "home",
    "Git": "Go",
    "git": "go",
    "Yenile": "Refresh",
    "yenile": "refresh",
    "Sil": "Delete",
    "sil": "delete",
    "Kopyala": "Copy",
    "kopyala": "copy",
    "kopyalandı": "copied",
    "kopyalanacak": "to be copied",
    "Kes": "Cut",
    "kes": "cut",
    "kesildi": "cut",
    "kesilecek": "to be cut",
    "Yapıştır": "Paste",
    "yapıştır": "paste",
    "yapıştırıldı": "pasted",
    "yapıştırılacak": "to be pasted",
    "Yeni": "New",
    "yeni": "new",
    "Aç": "Open",
    "aç": "open",
    "açılacak": "to be opened",
    "Tara": "Scan",
    "tara": "scan",
    "tarama": "scanning",
    "Analiz": "Analysis",
    "analiz": "analysis",
    "Organizasyon": "Organization",
    "organizasyon": "organization",
    "Duplikat": "Duplicate",
    "duplikat": "duplicate",
    "Göster": "Show",
    "göster": "show",
    "Başlat": "Start",
    "başlat": "start",
    "başlatılıyor": "starting",
    "Durdur": "Stop",
    "durdur": "stop",
    "İptal": "Cancel",
    "iptal": "cancel",
    "Tamam": "OK",
    "tamam": "ok",
    "Evet": "Yes",
    "evet": "yes",
    "Hayır": "No",
    "hayır": "no",
    "Uyarı": "Warning",
    "uyarı": "warning",
    "Hata": "Error",
    "hata": "error",
    "Bilgi": "Info",
    "bilgi": "info",
    "Onay": "Confirmation",
    "onay": "confirmation",
    "Hazır": "Ready",
    "hazır": "ready",
    "Tamamlandı": "Completed",
    "tamamlandı": "completed",
    "İşlem": "Operation",
    "işlem": "operation",
    "Boyut": "Size",
    "boyut": "size",
    "Tür": "Type",
    "tür": "type",
    "Adı": "Name",
    "adı": "name",
    "Yol": "Path",
    "yol": "path",
    "Tarih": "Date",
    "tarih": "date",
    "Saat": "Time",
    "saat": "time",
    "Süre": "Duration",
    "süre": "duration",
    "Kalan": "Remaining",
    "kalan": "remaining",
    "Geçen": "Elapsed",
    "geçen": "elapsed",
    "Toplam": "Total",
    "toplam": "total",
    "Sayı": "Count",
    "sayı": "count",
    "Adet": "Items",
    "adet": "items",
    "Öğe": "Item",
    "öğe": "item",
    "öğeler": "items",
    "Seçenek": "Option",
    "seçenek": "option",
    "Ayar": "Setting",
    "ayar": "setting",
    "ayarlar": "settings",
    "Konfigürasyon": "Configuration",
    "konfigürasyon": "configuration",
    
    # Specific phrases
    "Lütfen": "Please",
    "lütfen": "please",
    "bir dosya seçin": "select a file",
    "dosya seçin": "select file",
    "klasör seçin": "select folder",
    "silinecek dosya seçin": "select file to delete",
    "kopyalanacak dosya seçin": "select file to copy",
    "kesilecek dosya seçin": "select file to cut",
    "yeniden adlandırılacak dosya seçin": "select file to rename",
    "açılacak dosya seçin": "select file to open",
    "özelliklerini görmek istediğiniz dosyayı seçin": "select file to view properties",
    "yapıştırılacak dosya yok": "no file to paste",
    "tek dosya seçin": "select single file",
    "emin misiniz": "are you sure",
    "istediğinizden emin misiniz": "are you sure you want",
    "devam etmek istediğinizden emin misiniz": "are you sure you want to continue",
    "çıkmak istediğinizden emin misiniz": "are you sure you want to exit",
    "silmek istediğinizden emin misiniz": "are you sure you want to delete",
    "değiştirildi": "changed",
    "oluşturuldu": "created",
    "silindi": "deleted",
    "taşındı": "moved",
    "kopyalandı": "copied",
    "yapıştırıldı": "pasted",
    "yeniden adlandırıldı": "renamed",
    "açıldı": "opened",
    "kapatıldı": "closed",
    "başarılı": "successful",
    "başarısız": "failed",
    "tamamlandı": "completed",
    "iptal edildi": "cancelled",
    "durduruldu": "stopped",
    "devam ediyor": "continuing",
    "işleniyor": "processing",
    "bekleniyor": "waiting",
    "hazırlanıyor": "preparing",
    "kontrol ediliyor": "checking",
    "aranıyor": "searching",
    "bulunamadı": "not found",
    "bulundu": "found",
    "mevcut": "available",
    "mevcut değil": "not available",
    "geçerli": "valid",
    "geçersiz": "invalid",
    "doğru": "correct",
    "yanlış": "wrong",
    "boş": "empty",
    "dolu": "full",
    "açık": "open",
    "kapalı": "closed",
    "etkin": "active",
    "pasif": "inactive",
    "görünür": "visible",
    "gizli": "hidden",
    "dahil": "include",
    "hariç": "exclude",
    "ile": "with",
    "olmadan": "without",
    "için": "for",
    "göre": "according to",
    "kadar": "until",
    "sonra": "after",
    "önce": "before",
    "sırasında": "during",
    "esnasında": "while",
    "altında": "under",
    "üzerinde": "over",
    "içinde": "in",
    "dışında": "outside",
    "yanında": "next to",
    "arasında": "between",
    "karşısında": "opposite",
    "önünde": "in front of",
    "arkasında": "behind",
    
    # UI specific
    "Alt klasörleri dahil et": "Include Subfolders",
    "Gizli dosyaları dahil et": "Include Hidden Files",
    "Minimum boyut": "Min Size",
    "Maksimum boyut": "Max Size",
    "Uzantılar": "Extensions",
    "örn": "e.g.",
    "Duplikat kontrol": "Duplicate Check",
    "İsim": "Name",
    "Hash": "Hash",
    "Her seferinde sor": "Ask each time",
    "Otomatik atla": "Auto skip",
    "Numara ekleyerek taşı": "Copy with number",
    "Duplikat dosyalar için": "For duplicate files",
    "Dosya Adı": "File Name",
    "Klasör Yapısı": "Folder Structure",
    "Dosya Sayısı": "File Count",
    "Duplikat Dosya Grupları": "Duplicate File Groups",
    "Dosya Yolu": "File Path",
    "Değiştirilme": "Modified",
    "Oluşturulma": "Created",
    "Erişim": "Access",
    "Özellikler": "Properties",
    "Dosya Özellikleri": "File Properties",
    "Klasör Özellikleri": "Folder Properties",
    "Disk Analizi": "Disk Analysis",
    "Hedef Disk Analizi": "Target Disk Analysis",
    "İstatistikler": "Statistics",
    "Sonuçlar": "Results",
    "Rapor": "Report",
    "Dışa Aktar": "Export",
    "İçe Aktar": "Import",
    "Kaydet": "Save",
    "Yükle": "Load",
    "Çık": "Exit",
    "Kapat": "Close",
    "Gizle": "Hide",
    "Göster": "Show",
    "Büyüt": "Maximize",
    "Küçült": "Minimize",
    "Geri Al": "Undo",
    "Yinele": "Redo",
    "Kes": "Cut",
    "Kopyala": "Copy",
    "Yapıştır": "Paste",
    "Seç": "Select",
    "Tümünü Seç": "Select All",
    "Hiçbirini Seçme": "Select None",
    "Ters Seç": "Invert Selection",
    "Bul": "Find",
    "Değiştir": "Replace",
    "Sonraki": "Next",
    "Önceki": "Previous",
    "İlk": "First",
    "Son": "Last",
    "Sayfa": "Page",
    "Satır": "Line",
    "Sütun": "Column",
    "Tablo": "Table",
    "Liste": "List",
    "Ağaç": "Tree",
    "Menü": "Menu",
    "Araç Çubuğu": "Toolbar",
    "Durum Çubuğu": "Status Bar",
    "İlerleme Çubuğu": "Progress Bar",
    "Kaydırma Çubuğu": "Scroll Bar",
    "Sekme": "Tab",
    "Panel": "Panel",
    "Çerçeve": "Frame",
    "Pencere": "Window",
    "İletişim Kutusu": "Dialog",
    "Mesaj Kutusu": "Message Box",
    "Uyarı Kutusu": "Warning Box",
    "Hata Kutusu": "Error Box",
    "Bilgi Kutusu": "Info Box",
    "Onay Kutusu": "Confirmation Box",
    "Giriş Kutusu": "Input Box",
    "Parola Kutusu": "Password Box",
    "Metin Kutusu": "Text Box",
    "Sayı Kutusu": "Number Box",
    "Tarih Kutusu": "Date Box",
    "Saat Kutusu": "Time Box",
    "Renk Kutusu": "Color Box",
    "Dosya Kutusu": "File Box",
    "Klasör Kutusu": "Folder Box",
    "Resim Kutusu": "Image Box",
    "Video Kutusu": "Video Box",
    "Ses Kutusu": "Audio Box",
    "Bağlantı Kutusu": "Link Box",
    "E-posta Kutusu": "Email Box",
    "Telefon Kutusu": "Phone Box",
    "Adres Kutusu": "Address Box",
    "Harita Kutusu": "Map Box",
    "Grafik Kutusu": "Chart Box",
    "Tablo Kutusu": "Table Box",
    "Liste Kutusu": "List Box",
    "Açılır Liste": "Dropdown List",
    "Radyo Düğmesi": "Radio Button",
    "Onay Kutusu": "Checkbox",
    "Kaydırıcı": "Slider",
    "Döndürücü": "Spinner",
    "İlerleme Göstergesi": "Progress Indicator",
    "Yükleme Göstergesi": "Loading Indicator",
    "Bekleme Göstergesi": "Wait Indicator",
    "Durum Göstergesi": "Status Indicator",
    "Hata Göstergesi": "Error Indicator",
    "Uyarı Göstergesi": "Warning Indicator",
    "Bilgi Göstergesi": "Info Indicator",
    "Başarı Göstergesi": "Success Indicator",
    
    # Messages and notifications
    "Modüler dosya organizatörü hazır": "Modular file organizer ready",
    "Kaynak klasör seçerek başlayın": "Start by selecting source folder",
    "Önce kaynak klasör seçin": "Please select source folder first",
    "Önce hedef klasör seçin": "Please select target folder first",
    "Önce dosyaları tarayın": "Please scan files first",
    "Organizasyon başlatılacak": "Organization will start",
    "Devam etmek istediğinizden emin misiniz": "Are you sure you want to continue",
    "Organizasyon Onayı": "Organization Confirmation",
    "Organizasyon başlatılıyor": "Starting organization",
    "Organizasyon tamamlandı": "Organization completed",
    "Organizasyon hatası": "Organization error",
    "Silme Onayı": "Delete Confirmation",
    "dosyasını silmek istediğinizden emin misiniz": "are you sure you want to delete this file",
    "dosyayı silmek istediğinizden emin misiniz": "are you sure you want to delete these files",
    "öğe silindi": "items deleted",
    "öğe kopyalandı": "items copied",
    "öğe kesildi": "items cut",
    "öğe yapıştırıldı": "items pasted",
    "klasörü oluşturuldu": "folder created",
    "olarak değiştirildi": "renamed to",
    "açılamadı": "could not open",
    "silinemedi": "could not delete",
    "kopyalanamadı": "could not copy",
    "taşınamadı": "could not move",
    "yapıştırılamadı": "could not paste",
    "oluşturulamadı": "could not create",
    "yeniden adlandırılamadı": "could not rename",
    "Yeniden Adlandır": "Rename",
    "Yeni adı girin": "Enter new name",
    "Klasör adını girin": "Enter folder name",
    "Özellikler alınırken hata": "Error getting properties",
    "Ayarlar kaydedildi": "Settings saved",
    "Ayarlar yüklenemedi": "Could not load settings",
    "Bağlantı testi yapılıyor": "Testing connections",
    "Bağlantı testi tamamlandı": "Connection test completed",
    "bağlantısı doğru": "connection correct",
    "bağlantısı yanlış": "connection wrong",
    "bağlantısı düzeltildi": "connection fixed",
    "Modül bağlantıları kuruldu": "Module connections established",
    "Butonlar yeniden bağlandı": "Buttons rebound",
    "Event binding'ler yeniden bağlandı": "Events rebound",
    "Başlangıç ayarları tamamlandı": "Initial setup completed",
    "Modüler File Manager başlatıldı": "Modular File Manager initialized",
    "Modüler File Manager başlatılıyor": "Starting Modular File Manager",
    "Uygulama kesintiye uğradı": "Application interrupted",
    "Uygulama hatası": "Application error",
    "Başlatma Hatası": "Startup Error",
    "Uygulama başlatılamadı": "Failed to start application",
    "Çıkış": "Exit",
    "çıkmak istediğinizden emin misiniz": "are you sure you want to exit",
    
    # Time and progress
    "saniye": "seconds",
    "dakika": "minutes", 
    "saat": "hours",
    "gün": "days",
    "hafta": "weeks",
    "ay": "months",
    "yıl": "years",
    "Kalan süre": "Time remaining",
    "Geçen süre": "Elapsed time",
    "Tahmini süre": "Estimated time",
    "Hesaplanıyor": "Calculating",
    "Tamamlandı": "Completed",
    "İşleniyor": "Processing",
    "Bekleniyor": "Waiting",
    "Hazırlanıyor": "Preparing",
    "Başlatılıyor": "Starting",
    "Durduruluyor": "Stopping",
    "İptal ediliyor": "Cancelling",
    "Yeniden başlatılıyor": "Restarting",
    "Yenileniyor": "Refreshing",
    "Güncelleniyor": "Updating",
    "Kontrol ediliyor": "Checking",
    "Doğrulanıyor": "Verifying",
    "Onaylanıyor": "Confirming",
    "Kaydediliyor": "Saving",
    "Yükleniyor": "Loading",
    "İndiriliyor": "Downloading",
    "Yükleniyor": "Uploading",
    "Gönderiliyor": "Sending",
    "Alınıyor": "Receiving",
    "Bağlanıyor": "Connecting",
    "Bağlantı kesiliyor": "Disconnecting",
    "Aranıyor": "Searching",
    "Buluyor": "Finding",
    "Sıralıyor": "Sorting",
    "Filtreliyor": "Filtering",
    "Gruplıyor": "Grouping",
    "Karşılaştırıyor": "Comparing",
    "Analiz ediyor": "Analyzing",
    "Raporluyor": "Reporting",
    "Dışa aktarıyor": "Exporting",
    "İçe aktarıyor": "Importing",
    "Yedekliyor": "Backing up",
    "Geri yüklüyor": "Restoring",
    "Temizliyor": "Cleaning",
    "Optimize ediyor": "Optimizing",
    "Sıkıştırıyor": "Compressing",
    "Açıyor": "Extracting",
    "Şifreliyor": "Encrypting",
    "Şifre çözüyor": "Decrypting",
    "İmzalıyor": "Signing",
    "Doğruluyor": "Validating",
    "Test ediyor": "Testing",
    "Hata ayıklıyor": "Debugging",
    "Logluyor": "Logging",
    "İzliyor": "Monitoring",
    "Takip ediyor": "Tracking",
    "Kayıt ediyor": "Recording",
    "Oynatıyor": "Playing",
    "Duraklatıyor": "Pausing",
    "Durduruyor": "Stopping",
    "İleri sarıyor": "Fast forwarding",
    "Geri sarıyor": "Rewinding",
    "Tekrarlıyor": "Repeating",
    "Karıştırıyor": "Shuffling",
    "Seslendiriyor": "Announcing",
    "Bildiriyor": "Notifying",
    "Uyarıyor": "Warning",
    "Hata veriyor": "Erroring",
    "Başarı bildiriyor": "Success",
    "Bilgi veriyor": "Informing",
    "Yardım ediyor": "Helping",
    "Destekliyor": "Supporting",
    "Hizmet veriyor": "Serving",
    "Çalışıyor": "Working",
    "Aktif": "Active",
    "Pasif": "Inactive",
    "Meşgul": "Busy",
    "Boşta": "Idle",
    "Hazır": "Ready",
    "Bekleme": "Standby",
    "Uyku": "Sleep",
    "Kapalı": "Off",
    "Açık": "On",
    "Etkin": "Enabled",
    "Devre dışı": "Disabled",
    "Görünür": "Visible",
    "Gizli": "Hidden",
    "Kilitli": "Locked",
    "Kilitsiz": "Unlocked",
    "Güvenli": "Secure",
    "Güvensiz": "Insecure",
    "Genel": "Public",
    "Özel": "Private",
    "Paylaşımlı": "Shared",
    "Yerel": "Local",
    "Uzak": "Remote",
    "Çevrimiçi": "Online",
    "Çevrimdışı": "Offline",
    "Bağlı": "Connected",
    "Bağlı değil": "Disconnected",
    "Mevcut": "Available",
    "Mevcut değil": "Unavailable",
    "Erişilebilir": "Accessible",
    "Erişilemez": "Inaccessible",
    "Okunabilir": "Readable",
    "Okunamaz": "Unreadable",
    "Yazılabilir": "Writable",
    "Yazılamaz": "Unwritable",
    "Çalıştırılabilir": "Executable",
    "Çalıştırılamaz": "Non-executable",
    "Değiştirilebilir": "Modifiable",
    "Değiştirilemez": "Immutable",
    "Silinebilir": "Deletable",
    "Silinemez": "Undeletable",
    "Taşınabilir": "Movable",
    "Taşınamaz": "Immovable",
    "Kopyalanabilir": "Copyable",
    "Kopyalanamaz": "Non-copyable",
    "Yeniden adlandırılabilir": "Renamable",
    "Yeniden adlandırılamaz": "Non-renamable",
}

def translate_text(text):
    """Translate Turkish text to English"""
    # Sort by length (longest first) to avoid partial replacements
    sorted_translations = sorted(translations.items(), key=lambda x: len(x[0]), reverse=True)
    
    for turkish, english in sorted_translations:
        # Use word boundaries to avoid partial replacements
        pattern = r'\b' + re.escape(turkish) + r'\b'
        text = re.sub(pattern, english, text, flags=re.IGNORECASE)
    
    return text

def translate_file(input_file, output_file):
    """Translate a single file"""
    print(f"Translating {input_file} -> {output_file}")
    
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Translate content
        translated_content = translate_text(content)
        
        # Write translated content
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(translated_content)
        
        print(f"✅ Successfully translated {input_file}")
        
    except Exception as e:
        print(f"❌ Error translating {input_file}: {e}")

def main():
    """Main translation function"""
    print("🔄 Starting translation process...")
    
    # Files to translate
    files_to_translate = [
        ("main_modular_temp.py", "main_modular.py"),
        ("gui_manager_temp.py", "gui_manager.py"),
        ("file_operations_temp.py", "file_operations.py"),
        ("scan_engine_temp.py", "scan_engine.py"),
        ("reporting_temp.py", "reporting.py"),
    ]
    
    for temp_file, final_file in files_to_translate:
        if os.path.exists(temp_file):
            translate_file(temp_file, final_file)
        else:
            print(f"⚠️ File not found: {temp_file}")
    
    print("✅ Translation process completed!")
    
    # Clean up temp files
    print("🧹 Cleaning up temporary files...")
    for temp_file, _ in files_to_translate:
        if os.path.exists(temp_file):
            try:
                os.remove(temp_file)
                print(f"🗑️ Removed {temp_file}")
            except Exception as e:
                print(f"❌ Could not remove {temp_file}: {e}")

if __name__ == "__main__":
    main() 